name: Deploy Mafia Bot to VPS

on:
  push:
    branches: [ main ] # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a standard GitHub runner

    steps:
      - name: Deploy code via SSH
        uses: appleboy/ssh-action@v1.0.3 # Use a popular SSH action
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: | # Commands to run on the VPS
            echo "Starting deployment..."
            cd ~/Mafia-bot
            echo "Pulling latest code..."
            git pull origin main
            echo "Activating virtual environment..."
            source venv/bin/activate
            echo "Installing dependencies..."
            pip install -r requirements.txt
            echo "Stopping any old bot process..."
            pkill -f mafia_bot_main.py || true
            echo "Starting new bot process..."
            nohup python3 mafia_bot_main.py > nohup.out 2>&1 &
            echo "Deployment finished!"
